kind: pipeline
name: Build
trigger:
  event:
  - push
steps:
- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  environment:
    USERNAME:
      from_secret: LT_USERNAME
    PASSWORD:
      from_secret: LT_ACCESS_KEY
  settings:
    build_args_from_env:
    - USERNAME
    - PASSWORD
  commands:
  - ls
  - pwd
  - ps aux
  - sleep 1000
  
  
- name: test
  image: node
  environment:
    USERNAME:
      from_secret: LT_USERNAME
    PASSWORD:
      from_secret: LT_ACCESS_KEY
  settings:
    build_args_from_env:
    - USERNAME
    - PASSWORD
  commands:
  - npm install
  - npm test
