kind: pipeline
name: Build
trigger:
  event:
  - push
steps:
- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - ls
  - pwd
  
  
- name: build
  image: node
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - npm install
  - npm run single
