kind: pipeline
type: docker
name: Build
trigger:
  event:
  - push
steps:
- name: Tunnel
  image: lambdatest/tunnel
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - lambdatest/tunnel -user $LT_USERNAME -key $LT_ACCESS_KEY
  
- name: build
  image: node
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - npm install
  - npm run single
