kind: pipeline
name: Build
environment:
    PASSWORD:
      from_secret: LT_ACCESS_KEY
    USERNAME:
      from_secret: LT_USERNAME
trigger:
  event:
  - push
steps: 
- name: build
  image: node
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - export LT_USERNAME= $USERNAME
  - export LT_ACCESS_KEY= $PASSWORD
  - npm install
  - npm run single

- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  settings:
    build_args_from_env:
    - USERNAME
    - PASSWORD
  commands:
  - ls
  - curl 127.0.0.1:13001/api/v1.0/info
