kind: pipeline
name: Build
trigger:
  event:
  - push
steps:
- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  environment:
    user:
      from_secret: LT_USERNAME
    key:
      from_secret: LT_ACCESS_KEY
  settings:
    build_args_from_env:
    - user
    - key
  commands:
  - ls
  - pwd
  - ps aux
  - sleep 100
  
  
- name: test
  image: node
  environment:
    user:
      from_secret: LT_USERNAME
    key:
      from_secret: LT_ACCESS_KEY
  settings:
    build_args_from_env:
    - user
    - key
  commands:
  - export LT_USERNAME=$user
  - export LT_ACCESS_KEY=$key
  - npm install
