kind: pipeline
name: Build
trigger:
  event:
  - push
steps: 
- name: Test
  image: node
  environment:
    PASSWORD:
      from_secret: LT_ACCESS_KEY
    USERNAME:
      from_secret: LT_USERNAME
  commands:
  - export LT_USERNAME=$USERNAME
  - export LT_ACCESS_KEY=$PASSWORD
  - npm install
  - npm run single

- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  settings:
    build_args_from_env:
    - USERNAME
    - PASSWORD
  commands:
  - ls
  - curl 127.0.0.1:13001/api/v1.0/info
