kind: pipeline
name: Build
trigger:
  event:
  - push
steps:
- name: Tunnel
  type: docker
  image: lambdatest/tunnel
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - ls
  - curl 127.0.0.1:13001/api/v1.0/info
  
- name: build
  image: node
  secrets: [LT_USERNAME, LT_ACCESS_KEY]
  commands:
  - npm install
  - npm run single
