kind: pipeline
name: Build
trigger:
  event:
  - push
steps: 
- name: Test
  image: node
  environment:
    PASSWORD:
      from_secret: LT_ACCESS_KEY
    USERNAME:
      from_secret: LT_USERNAME
  commands:
  - export LT_USERNAME=$USERNAME
  - export LT_ACCESS_KEY=$PASSWORD
  - npm install
  - npm run single

- name: Tunnel
  image: lambdatest/tunnel
  environment:
    PASSWORD:
      from_secret: LT_ACCESS_KEY
    USERNAME:
      from_secret: LT_USERNAME
  commands:
  - docker pull lambdatest/tunnel
  - docker run -it --name lt lambdatest/tunnel -user $USERNAME -key $PASSWORD
